// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh manifest`.

import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/portfolio/[project].tsx";
import * as $3 from "./routes/portfolio/index.tsx";
import * as $4 from "./routes/resume.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/index.tsx": $1,
    "./routes/portfolio/[project].tsx": $2,
    "./routes/portfolio/index.tsx": $3,
    "./routes/resume.tsx": $4,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
